# **What is NumPy?**

NumPy is a Python library used for working with arrays.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.



# **Why Use NumPy?**

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

**Arrays are very frequently used in data science, where speed and resources are very important.**

# **Why is NumPy Faster Than Lists?**

NumPy is faster than lists because it is designed to efficiently process large arrays and matrices of numerical data. NumPy is implemented in C and uses contiguous blocks of memory, which makes it faster to perform mathematical operations on arrays because it avoids the overhead of type-checking and other operations that can slow down Python lists. Additionally, NumPy has built-in functions for common mathematical operations, such as dot products and linear algebra operations, which are optimized for performance. In contrast, Python lists are not designed for numerical computations and are slower because they are implemented in Python, which is an interpreted language that requires more time to execute each statement.

Lets get started.......

In [60]:
import numpy 

You can use NumPy now that it has been imported.




In [61]:
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


Create an alias with the **as** keyword while importing:

**alias**: In Python alias are an alternate name for referring to the same thing.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
print(np.__version__)

1.22.4


# **Create a NumPy ndarray Object**

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

***Note*** : "nd" stands for "n-dimensional" in ndarray. It refers to the fact that ndarray is capable of representing arrays with any number of dimensions (or axes). For example, a 1-dimensional array is a vector, a 2-dimensional array is a matrix, and an array with three or more dimensions is a tensor.

To create a NumPy ndarray object, we can utilize the array() function.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

In [ ]:
type(arr)

numpy.ndarray

**type()** is a built-in Python function that allows us to determine the type of an object that is passed as its argument. In the context of the code above, it shows that the variable arr is of type numpy.ndarray.

Use a tuple to create a NumPy array:

In [ ]:
a = np.array((1, 2, 3, 4, 5))
a

array([1, 2, 3, 4, 5])

*Difference Between Tuple and array*



2.  Type: A tuple can hold different types of data such as strings, integers, and other tuples. An array can only hold a single type of data such as integers, floats, or booleans.

3.  Size: Tuples are usually used for smaller collections of data, while arrays are used for larger collections of data.



4.   Memory allocation: In most programming languages, tuples are stored in a contiguous block of memory, whereas arrays may be stored in a non-contiguous block of memory.


5.   Usage: Tuples are commonly used for data that won't change, such as coordinates, while arrays are commonly used for storing and manipulating large amounts of data, such as matrices or data sets.

## **Dimensions in Arrays**

A dimension in arrays is one level of array depth (nested arrays).

**nested array :** are arrays that have arrays as their elements.

# 0-D Arrays

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [ ]:
arr = np.array(42)
arr

array(42)

# 1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

arr

array([1, 2, 3, 4, 5])

# 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

# 3-D arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

# **How to check Number of Dimensions?**

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [67]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3]]])



d.ndim


3

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [66]:
arr = np.array([1, 2, 3, 4], ndmin=3)

print(arr)
print('number of dimensions :', arr.ndim)

[[[1 2 3 4]]]
number of dimensions : 3


# **NumPy Array Indexing**

# Access Array Elements

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [ ]:
arr = np.array([1, 2, 3, 4])
arr[0]

1

In [ ]:
arr[1]

2

In [ ]:
arr[2]+arr[3]

7

# Access 2-D Arrays

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [ ]:
print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


# Access 3-D Arrays

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:

[[1, 2, 3], [4, 5, 6]]

and:

[[7, 8, 9], [10, 11, 12]]

Since we selected 0, we are left with the first array: 
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3] 
and:
[4, 5, 6]

Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:

4

5

6

Since we selected 2, we end up with the third value: 
6

# **Negative Indexing**

Use negative indexing to access an array from the end.

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# **NumPy Array Slicing**

# Slicing arrays

Slicing an array in Python means selecting a portion of an array by specifying the starting and ending indices of the portion to be selected.


```
new_array = old_array[start:end]
```
Here, start is the starting index of the portion to be selected and end is the ending index (exclusive) of the portion to be selected. The selected portion of the array is returned as a new array.




In [69]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [70]:
arr[4:]

array([5, 6, 7])

In [71]:
arr[:4]

array([1, 2, 3, 4])

In [72]:
arr[-3:-1]

array([5, 6])

# STEP

Use the step value to determine the step of the slicing:

Return every other element from index 1 to index 5:

In [75]:
arr[1:6:2]

array([2, 4, 6])

Return every other element from the entire array:

In [76]:
arr[::2]

array([1, 3, 5, 7])

# Slicing 2-D Arrays

From the second element, slice elements from index 1 to index 4 (not included):

In [77]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[1, 1:4]

array([7, 8, 9])

From both elements, return index 2:

In [ ]:
arr[0:2, 2]

From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

In [ ]:
print(arr[0:2, 1:4])

# **Data Types in NumPy**

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

# Checking the Data Type of an Array

The NumPy array object has a property called dtype that returns the data type of the array:


In [ ]:
arr = np.array([1, 2, 3, 4])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])
arr.dtype

dtype('<U6')

# Creating Arrays With a Defined Data Type

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')
arr.dtype

dtype('S1')

# **Shape of an Array**

The shape of an array is the number of elements in each dimension.

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr.shape

(2, 4)

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)
arr.shape



(1, 1, 1, 1, 4)

In [ ]:
print(arr)

[[[[[1 2 3 4]]]]]


# Reshape From 1-D to 2-D

Convert 1-D array with 12 elements into a 2-D array with 4 arrays, each containing 3 elements in the outermost dimension.

In [82]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
newarr= arr.reshape(2,6)
newarr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

Do it by yourself:

Reshape From 1-D to 3-D

In [87]:
newarr = arr.reshape(2,2,3)
newarr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# Iterating Arrays

If we iterate on a 1-D array it will go through each element one by one.

In [ ]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [91]:
arr = np.array([[1,2,3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [89]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


# Splitting NumPy Arrays

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [92]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

newarr

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [94]:
arr=[4,56,81,741,6451,62,6]
arr.sort()

In [95]:
arr

[4, 6, 56, 62, 81, 741, 6451]